apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-job-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-create
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "jobs", "services"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-create-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kubectl-job-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-create
  apiGroup: rbac.authorization.k8s.io
